### ISSUE TITLE
Help text shows config option twice

### ISSUE THREAD

**Issue by rasa** [kdeldycke/click-extra#173]
# Synopsis

Using click-extra, 2.1.1, when I use `make_pass_decorator` with `config_option`, the text
```
  -C, --config CONFIG_PATH  Location of the configuration file. Supports both
                            local path and remote URL.  [default:config.{toml,yaml,yml,json,ini,xml}]
```
appears twice in the help text.

# Details

The code:

```python
import click

class Ex:
    pass

pass_class = click.make_pass_decorator(Ex)

@click.group()
@click.pass_context
def cli(ctx):
    ctx.obj = Ex()

@cli.command()
@pass_class
def command():
    pass

if __name__ == "__main__":
    cli()
```
produces:
```console
Usage: test.py [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  command
```
and replacing `click` with `click_extra` in the above code:
```python
import click_extra as click # replaced click with click_extra

class Ex:
    pass

pass_class = click.make_pass_decorator(Ex)

@click.group()
@click.pass_context
def cli(ctx):
    ctx.obj = Ex()

@cli.command()
@pass_class
def command():
    pass

if __name__ == "__main__":
    cli()
```
produces:
```console
Usage: test.py [OPTIONS] COMMAND [ARGS]...

Options:
  --time / --no-time        Measure and print elapsed execution time.  [default:
                            no-time]
  --color, --ansi / --no-color, --no-ansi
                            Strip out all colors and all ANSI codes from output.
                            [default: color]
  -C, --config CONFIG_PATH  Location of the configuration file. Supports both
                            local path and remote URL.  [default:config.{toml,yaml,yml,json,ini,xml}]
  -v, --verbosity LEVEL     Either CRITICAL, ERROR, WARNING, INFO, DEBUG.
                            [default: INFO]
  --version                 Show the version and exit.
  -h, --help                Show this message and exit.

Commands:
  command
```
which is unexpected, as I didn't use `verbosity_option`, etc, but it's fine.

But when I add `config_option` to the above code:
```python
import click_extra as click

class Ex:
    pass

pass_class = click.make_pass_decorator(Ex)

@click.group()
@click.config.config_option() # added this line
@click.pass_context
def cli(ctx):
    ctx.obj = Ex()

@cli.command()
@pass_class
def command():
    pass

if __name__ == "__main__":
    cli()
```
The `--config` option now appears twice:
```console
Usage: test.py [OPTIONS] COMMAND [ARGS]...

Options:
  -C, --config CONFIG_PATH  Location of the configuration file. Supports both
                            local path and remote URL.  [default:config.{toml,yaml,yml,json,ini,xml}]
  --time / --no-time        Measure and print elapsed execution time.  [default:
                            no-time]
  --color, --ansi / --no-color, --no-ansi
                            Strip out all colors and all ANSI codes from output.
                            [default: color]
  -C, --config CONFIG_PATH  Location of the configuration file. Supports both
                            local path and remote URL.  [default:config.{toml,yaml,yml,json,ini,xml}]
  -v, --verbosity LEVEL     Either CRITICAL, ERROR, WARNING, INFO, DEBUG.
                            [default: INFO]
  --version                 Show the version and exit.
  -h, --help                Show this message and exit.

Commands:
  command
```
I would try to fix, but perhaps all of these options (config/time/color/verbosity) shouldn't be showing up by default, which is a bigger change.

**Comment by kdeldycke** [comment]
Oh.

In my first iteration of `click-extra` I wanted all the bells and whistles to be automatically applied out of the box to any `group`/`command` structure. To reduce the work done by new users and show them off its advantages. That's why all the options pop-up by default in your examples.

It's only after a while I realized I can speed-up the adoption of `click-extra` by advertising it as a drop-in replacement for `click`, but with extras.

Of course the 2 approaches are now conflicting and you're getting confused. I guess the best course of action is to detach all these default options on `group` and `command`, and let the user adds them as they see fit.

What do you think?

**Comment by rasa** [comment]
While I personally don't mind all the options being enabled by default, my guess is most users will want to enable them manually. Perhaps they're all off by default, but then have an `@every_option` or `@all_options` to easily pull in everything.

**Comment by kdeldycke** [comment]
For the record, the default `command` and `group` imported from `click_extra` is now longer attached with all the defaults options. Nor it is coming with all bells and whistles. In fact `command` and `group` are now an alias to Cloup's. So `click_extra` is now a drop-in replacement without surprises.

If you need all the previous behaviour, use `extra_command` instead of `command` and `extra_group` instead of `group`.

This huge refactor has been pushed upstream and lots of polishing is still required. It will be part of the upcoming v3.0.0 release.

Nice side effect of the refactoring: it solves the duplicate option and confusing bug you reported initially since all options can now be used standalone too.

**Comment by kdeldycke** [comment]
And to try to make things easier to grasp, I've written a first draft of a tutorial at: https://kdeldycke.github.io/click-extra/tutorial.html
