### ISSUE TITLE
Default config location should follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by raj-magesh** [kdeldycke/click-extra#211]
According to the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html), config files should be stored under `$XDG_CONFIG_HOME/<application>` (which defaults to `~/.config/application` when `$XDG_CONFIG_HOME` is not set) and it would good to change the default config file location to match this.

**Comment by kdeldycke** [comment]
I was under the impression that the [`click.get_app_dir()`](https://github.com/pallets/click/blob/bf9da4838986af3bc09a1b16974d154c61dcbe3f/src/click/utils.py#L403-L449) method I use was doing just that.

But double-checking the code yes, I'm [using a `force_posix=True`](https://github.com/kdeldycke/click-extra/blob/c2d8fb54c8ef84323f84dd332631e4334da01eee/click_extra/config.py#L104) parameter.

I guess I did it because I initially wanted to have both macOS & Linux configuration in the same location, i.e. `~/.<application>/`.

But you're right, maybe I should let `click.get_app_dir()` do its job and expose `force_posix` has an additional parameter.

**Comment by kdeldycke** [comment]
Hey @raj-magesh, I just integrated [click.get_app_dir()](https://github.com/pallets/click/blob/bf9da4838986af3bc09a1b16974d154c61dcbe3f/src/click/utils.py#L403-L449) with the configuration option.

All is documented here: https://kdeldycke.github.io/click-extra/config.html#default-folder

Now you can have an influence on the default directory with the `roaming` and `force_posix` arguments like Click does. And yes, by default, it respects the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

This will be available in click-extra v3.1.0 that I'm about to release.
